#!/usr/bin/env python3
"""Generate a fresh 40-topic Flutter open-source showcase batch in EN and VI."""
from __future__ import annotations

from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT_EN = ROOT / "src" / "content" / "blog"
OUT_VI = ROOT / "src" / "content" / "blog-vi"
DATE = "2026-09-16"
AUTHOR = "Trung Hieu"
HERO = "/blog/images/fluttercook-editorial-2026.svg"


TOPICS = [
    dict(slug="oss-go-router", package="go_router", title="go_router: URL-first navigation for Flutter", vi="go_router: Điều hướng Flutter lấy URL làm trung tâm", focus="declarative routing, deep links, redirects, and ShellRoute", vi_focus="routing khai báo, deep link, redirect và ShellRoute", code="""final router = GoRouter(\n  redirect: (context, state) => isSignedIn || state.uri.path == '/login'\n      ? null\n      : '/login',\n  routes: [\n    GoRoute(path: '/', builder: (_, __) => const HomePage()),\n    GoRoute(path: '/orders/:id', builder: (_, state) =>\n        OrderPage(id: state.pathParameters['id']!)),\n  ],\n);""", pitfall="Do not hide auth redirects inside widgets; they belong at the route boundary.", vi_pitfall="Đừng giấu redirect xác thực trong widget; hãy đặt nó ở ranh giới route.", sources=[("go_router on pub.dev", "https://pub.dev/packages/go_router"), ("go_router repository", "https://github.com/flutter/packages/tree/main/packages/go_router")], tags=["Flutter", "OpenSource", "Routing"]),
    dict(slug="oss-riverpod", package="riverpod", title="Riverpod: testable async state without widget coupling", vi="Riverpod: state bất đồng bộ có thể test mà không dính widget", focus="providers, async states, caching, and dependency overrides", vi_focus="provider, trạng thái async, cache và override dependency", code="""final usersProvider = FutureProvider<List<User>>((ref) async {\n  final api = ref.watch(apiProvider);\n  return api.fetchUsers();\n});\n\nclass UsersView extends ConsumerWidget {\n  const UsersView({super.key});\n  @override\n  Widget build(BuildContext context, WidgetRef ref) =>\n      ref.watch(usersProvider).when(\n        data: (users) => UserList(users),\n        loading: () => const CircularProgressIndicator(),\n        error: (error, stack) => Text('Failed: $error'),\n      );\n}""", pitfall="A provider graph is not a replacement for a domain boundary; keep API models out of UI state.", vi_pitfall="Cây provider không thay thế boundary domain; đừng đưa API model thẳng vào UI state.", sources=[("Riverpod on pub.dev", "https://pub.dev/packages/riverpod"), ("Riverpod documentation", "https://riverpod.dev/")], tags=["Flutter", "OpenSource", "State"]),
    dict(slug="oss-flutter-bloc", package="flutter_bloc", title="flutter_bloc: explicit events and states at scale", vi="flutter_bloc: event và state rõ ràng cho ứng dụng lớn", focus="Cubit, Bloc, BlocListener, and predictable state transitions", vi_focus="Cubit, Bloc, BlocListener và chuyển trạng thái dễ dự đoán", code="""sealed class CheckoutState {}\nfinal class CheckoutIdle extends CheckoutState {}\nfinal class CheckoutSubmitting extends CheckoutState {}\nfinal class CheckoutDone extends CheckoutState {}\n\nclass CheckoutCubit extends Cubit<CheckoutState> {\n  CheckoutCubit(this.repository) : super(CheckoutIdle());\n  final CheckoutRepository repository;\n  Future<void> submit(Order order) async {\n    emit(CheckoutSubmitting());\n    await repository.submit(order);\n    emit(CheckoutDone());\n  }\n}""", pitfall="Keep side effects in BlocListener and render state in BlocBuilder; mixing them causes duplicate work.", vi_pitfall="Đặt side effect trong BlocListener và render trong BlocBuilder; trộn hai nơi dễ chạy lặp.", sources=[("flutter_bloc on pub.dev", "https://pub.dev/packages/flutter_bloc"), ("Bloc documentation", "https://bloclibrary.dev/")], tags=["Flutter", "OpenSource", "Bloc"]),
    dict(slug="oss-freezed", package="freezed", title="Freezed: safer immutable models and unions", vi="Freezed: model bất biến và union an toàn hơn", focus="immutable data classes, JSON unions, copyWith, and exhaustive UI states", vi_focus="data class bất biến, JSON union, copyWith và state UI exhaustive", code="""@freezed\nsealed class LoadState<T> with _$LoadState<T> {\n  const factory LoadState.idle() = Idle<T>;\n  const factory LoadState.loading() = Loading<T>;\n  const factory LoadState.data(T value) = Data<T>;\n  const factory LoadState.failure(Object error) = Failure<T>;\n}""", pitfall="Commit generated files only when your repository policy requires it; otherwise make code generation part of CI.", vi_pitfall="Chỉ commit file generated khi policy repo yêu cầu; nếu không, hãy chạy codegen trong CI.", sources=[("freezed on pub.dev", "https://pub.dev/packages/freezed"), ("Freezed repository", "https://github.com/rrousselGit/freezed")], tags=["Flutter", "OpenSource", "Codegen"]),
    dict(slug="oss-drift-database", package="drift", title="Drift: typed SQL for an offline-first Flutter app", vi="Drift: SQL có kiểu cho ứng dụng Flutter offline-first", focus="typed tables, migrations, reactive queries, and transactions", vi_focus="table có kiểu, migration, query reactive và transaction", code="""@DriftDatabase(tables: [Todos])\nclass AppDatabase extends _$AppDatabase {\n  AppDatabase(super.e);\n  @override\n  int get schemaVersion => 1;\n\n  Stream<List<Todo>> watchOpenTodos() =>\n      (select(todos)..where((t) => t.done.equals(false))).watch();\n}""", pitfall="Treat migrations as production code and test old schemas before shipping an upgrade.", vi_pitfall="Migration là code production; hãy test schema cũ trước khi phát hành bản nâng cấp.", sources=[("Drift on pub.dev", "https://pub.dev/packages/drift"), ("Drift documentation", "https://drift.simonbinder.eu/")], tags=["Flutter", "OpenSource", "Database"]),
    dict(slug="oss-isar-database", package="isar", title="Isar: fast local objects with queryable indexes", vi="Isar: object database local nhanh với index có thể query", focus="collections, indexes, transactions, and reactive watchers", vi_focus="collection, index, transaction và watcher reactive", code="""@collection\nclass Note {\n  Id id = Isar.autoIncrement;\n  late String title;\n  @Index()\n  late DateTime updatedAt;\n}\n\nawait isar.writeTxn(() async {\n  await isar.notes.put(note);\n});""", pitfall="Choose indexes from real query patterns; every index has a write and storage cost.", vi_pitfall="Chọn index từ query thực tế; mỗi index đều có chi phí ghi và dung lượng.", sources=[("Isar on pub.dev", "https://pub.dev/packages/isar"), ("Isar repository", "https://github.com/isar/isar")], tags=["Flutter", "OpenSource", "Database"]),
    dict(slug="oss-dio-networking", package="dio", title="Dio: composeable networking with interceptors", vi="Dio: networking có thể ghép bằng interceptor", focus="interceptors, cancellation, retries, and typed error mapping", vi_focus="interceptor, hủy request, retry và ánh xạ lỗi có kiểu", code="""final dio = Dio(BaseOptions(baseUrl: apiBaseUrl));\n\ndio.interceptors.add(InterceptorsWrapper(\n  onRequest: (options, handler) {\n    options.headers['Authorization'] = 'Bearer $token';\n    handler.next(options);\n  },\n  onError: (error, handler) {\n    logApiFailure(error);\n    handler.next(error);\n  },\n));""", pitfall="Retries must be limited to idempotent operations or guarded by an idempotency key.", vi_pitfall="Retry chỉ nên áp dụng cho thao tác idempotent hoặc có idempotency key.", sources=[("Dio on pub.dev", "https://pub.dev/packages/dio"), ("Dio repository", "https://github.com/cfug/dio")], tags=["Flutter", "OpenSource", "Networking"]),
    dict(slug="oss-sentry-flutter", package="sentry_flutter", title="Sentry Flutter: errors with release context", vi="Sentry Flutter: lỗi đi kèm context của release", focus="crash reporting, performance traces, breadcrumbs, and source maps", vi_focus="crash report, trace hiệu năng, breadcrumb và source map", code="""await SentryFlutter.init(\n  (options) {\n    options.dsn = const String.fromEnvironment('SENTRY_DSN');\n    options.tracesSampleRate = 0.1;\n    options.environment = const String.fromEnvironment('APP_ENV');\n  },\n  appRunner: () => runApp(const App()),\n);""", pitfall="Never ship a DSN or event payload containing tokens, passwords, or raw user content.", vi_pitfall="Không gửi token, password hay nội dung người dùng thô vào event; DSN không phải secret.", sources=[("sentry_flutter on pub.dev", "https://pub.dev/packages/sentry_flutter"), ("Sentry Flutter docs", "https://docs.sentry.io/platforms/flutter/")], tags=["Flutter", "OpenSource", "Observability"]),
    dict(slug="oss-patrol-testing", package="patrol", title="Patrol: integration tests that can leave the Flutter sandbox", vi="Patrol: integration test có thể đi ra ngoài sandbox Flutter", focus="native permissions, notifications, deep links, and device automation", vi_focus="permission native, notification, deep link và tự động hóa thiết bị", code="""patrolTest('camera permission flow', ($) async {\n  await $.native.grantPermissionWhenInUse();\n  await $.pumpWidgetAndSettle(const CameraApp());\n  await $(#takePhoto).tap();\n  expect(find.byType(PhotoPreview), findsOneWidget);\n});""", pitfall="Keep native setup deterministic; a test that depends on a previously granted permission is flaky.", vi_pitfall="Native setup phải deterministic; test dựa vào permission đã cấp từ trước sẽ flaky.", sources=[("Patrol on pub.dev", "https://pub.dev/packages/patrol"), ("Patrol repository", "https://github.com/leancodepl/patrol")], tags=["Flutter", "OpenSource", "Testing"]),
    dict(slug="oss-rive-runtime", package="rive", title="Rive: interactive vector animation as a state machine", vi="Rive: animation vector tương tác bằng state machine", focus="artboards, state machines, inputs, and runtime performance", vi_focus="artboard, state machine, input và hiệu năng runtime", code="""final controller = StateMachineController.fromArtboard(\n  artboard,\n  'LoginMachine',\n);\nif (controller != null) {\n  artboard.addController(controller);\n  final success = controller.findInput<bool>('success');\n  success?.value = true;\n}""", pitfall="Keep animation state in the artboard controller, not in a rebuild-heavy widget tree.", vi_pitfall="Giữ animation state trong artboard controller, không đặt vào widget tree rebuild quá nhiều.", sources=[("Rive on pub.dev", "https://pub.dev/packages/rive"), ("Rive Flutter repository", "https://github.com/rive-app/rive-flutter")], tags=["Flutter", "OpenSource", "Animation"]),
    dict(slug="oss-flex-color-scheme", package="flex_color_scheme", title="FlexColorScheme: design-system themes without boilerplate", vi="FlexColorScheme: theme design system ít boilerplate", focus="light/dark schemes, surface blends, seed colors, and Material 3", vi_focus="scheme sáng/tối, surface blend, seed color và Material 3", code="""MaterialApp(\n  theme: FlexThemeData.light(scheme: FlexScheme.mandyRed),\n  darkTheme: FlexThemeData.dark(scheme: FlexScheme.mandyRed),\n  themeMode: ThemeMode.system,\n  home: const HomePage(),\n);""", pitfall="Treat the package as theme composition, not a substitute for your own semantic color tokens.", vi_pitfall="Xem package là lớp ghép theme, không phải thay thế semantic color token của bạn.", sources=[("FlexColorScheme on pub.dev", "https://pub.dev/packages/flex_color_scheme"), ("FlexColorScheme docs", "https://docs.flexcolorscheme.com/")], tags=["Flutter", "OpenSource", "DesignSystem"]),
    dict(slug="oss-shadcn-flutter-components", package="shadcn_flutter", title="shadcn_flutter: composable UI primitives for Flutter", vi="shadcn_flutter: UI primitive có thể ghép cho Flutter", focus="unstyled primitives, New York style, Material interop, and theming", vi_focus="primitive ít áp đặt style, phong cách New York, Material interop và theme", code="""runApp(\n  ShadcnApp(\n    theme: ThemeData(colorScheme: ColorSchemes.lightZinc()),\n    home: Scaffold(\n      body: Center(\n        child: PrimaryButton(child: const Text('Continue')),\n      ),\n    ),\n  ),\n);""", pitfall="Decide where Material ends and shadcn components begin; a mixed screen needs one clear spacing system.", vi_pitfall="Hãy xác định Material dừng ở đâu và shadcn bắt đầu ở đâu; màn hình trộn cần một spacing system rõ ràng.", sources=[("shadcn_flutter on pub.dev", "https://pub.dev/packages/shadcn_flutter"), ("shadcn_flutter repository", "https://github.com/sunarya-thito/shadcn_flutter")], tags=["Flutter", "OpenSource", "UI"]),
    dict(slug="oss-forui-components", package="forui", title="ForUI: accessible headless components for Flutter", vi="ForUI: component headless dễ tiếp cận cho Flutter", focus="composable controls, theming, keyboard behavior, and accessibility", vi_focus="control có thể ghép, theme, keyboard behavior và accessibility", code="""FButton(\n  onPress: submit,\n  child: const Text('Save'),\n);\n\nFPopoverMenu(\n  control: FButton(onPress: openMenu, child: const Text('More')),\n  menu: [\n    FPopoverMenuItem(onPress: archive, child: const Text('Archive')),\n  ],\n);""", pitfall="Run semantics and keyboard tests on every supported platform; visual similarity is not accessibility.", vi_pitfall="Chạy test semantics và keyboard trên mọi platform; giống ảnh không có nghĩa là accessible.", sources=[("ForUI on pub.dev", "https://pub.dev/packages/forui"), ("ForUI repository", "https://github.com/forus-labs/forui")], tags=["Flutter", "OpenSource", "Accessibility"]),
    dict(slug="oss-supabase-flutter", package="supabase_flutter", title="supabase_flutter: auth, Postgres, realtime, and storage", vi="supabase_flutter: auth, Postgres, realtime và storage", focus="typed client initialization, auth events, RLS, and session persistence", vi_focus="khởi tạo client có kiểu, auth event, RLS và lưu session", code="""await Supabase.initialize(\n  url: const String.fromEnvironment('SUPABASE_URL'),\n  publishableKey: const String.fromEnvironment('SUPABASE_KEY'),\n);\n\nfinal supabase = Supabase.instance.client;\nawait supabase.auth.signInWithPassword(\n  email: email,\n  password: password,\n);""", pitfall="RLS is part of the security boundary; never treat a publishable key as permission to skip database policies.", vi_pitfall="RLS là một phần security boundary; publishable key không cho phép bỏ qua policy database.", sources=[("supabase_flutter on pub.dev", "https://pub.dev/packages/supabase_flutter"), ("Supabase Flutter quickstart", "https://supabase.com/docs/guides/getting-started/quickstarts/flutter")], tags=["Flutter", "OpenSource", "Backend"]),
    dict(slug="oss-appwrite-flutter", package="appwrite", title="Appwrite Flutter: backend services with explicit clients", vi="Appwrite Flutter: backend service với client rõ ràng", focus="endpoint/project configuration, auth, databases, storage, and functions", vi_focus="cấu hình endpoint/project, auth, database, storage và function", code="""final client = Client()\n  .setEndpoint('https://cloud.appwrite.io/v1')\n  .setProject(projectId);\n\nfinal account = Account(client);\nawait account.createEmailPasswordSession(\n  email: email,\n  password: password,\n);""", pitfall="Keep project IDs and environments explicit; do not silently point staging builds at production.", vi_pitfall="Khai báo rõ project ID và environment; đừng để build staging trỏ nhầm production.", sources=[("Appwrite Flutter on pub.dev", "https://pub.dev/packages/appwrite"), ("Appwrite Flutter SDK", "https://github.com/appwrite/sdk-for-flutter")], tags=["Flutter", "OpenSource", "Backend"]),
    dict(slug="oss-flutter-secure-storage", package="flutter_secure_storage", title="flutter_secure_storage: secrets behind platform keychains", vi="flutter_secure_storage: secret nằm sau keychain của platform", focus="Keychain, Keystore, encrypted shared preferences, and migration", vi_focus="Keychain, Keystore, encrypted shared preferences và migration", code="""const storage = FlutterSecureStorage();\nawait storage.write(key: 'refresh_token', value: refreshToken);\nfinal token = await storage.read(key: 'refresh_token');\nawait storage.delete(key: 'refresh_token');""", pitfall="Secure storage is for small secrets, not an offline database or a replacement for server-side revocation.", vi_pitfall="Secure storage dành cho secret nhỏ, không phải database offline hay cơ chế revoke phía server.", sources=[("flutter_secure_storage on pub.dev", "https://pub.dev/packages/flutter_secure_storage"), ("flutter_secure_storage repository", "https://github.com/juliansteenbakker/flutter_secure_storage")], tags=["Flutter", "OpenSource", "Security"]),
    dict(slug="oss-local-auth", package="local_auth", title="local_auth: biometrics as a step-up, not a password store", vi="local_auth: biometric là step-up, không phải nơi lưu password", focus="device support, biometric prompts, fallback credentials, and failure UX", vi_focus="hỗ trợ thiết bị, prompt biometric, credential fallback và UX lỗi", code="""final auth = LocalAuthentication();\nfinal supported = await auth.isDeviceSupported();\nif (supported) {\n  final ok = await auth.authenticate(\n    localizedReason: 'Unlock your saved account',\n    options: const AuthenticationOptions(biometricOnly: false),\n  );\n  if (ok) unlock();\n}""", pitfall="Biometric success proves local user presence; still require server/session checks for sensitive actions.", vi_pitfall="Biometric thành công chỉ chứng minh người dùng hiện diện trên máy; thao tác nhạy cảm vẫn cần session/server check.", sources=[("local_auth on pub.dev", "https://pub.dev/packages/local_auth"), ("Flutter local_auth plugin", "https://github.com/flutter/packages/tree/main/packages/local_auth")], tags=["Flutter", "OpenSource", "Security"]),
    dict(slug="oss-permission-handler", package="permission_handler", title="permission_handler: runtime permission flows you can explain", vi="permission_handler: luồng xin quyền runtime có thể giải thích", focus="status, rationale, settings fallback, and platform declarations", vi_focus="status, rationale, mở settings fallback và khai báo platform", code="""final status = await Permission.camera.request();\nif (status.isGranted) {\n  openCamera();\n} else if (status.isPermanentlyDenied) {\n  await openAppSettings();\n}""", pitfall="Request only the permission needed for the current user action and explain why before the OS prompt.", vi_pitfall="Chỉ xin quyền cần cho action hiện tại và giải thích trước khi hiện prompt của OS.", sources=[("permission_handler on pub.dev", "https://pub.dev/packages/permission_handler"), ("permission_handler repository", "https://github.com/Baseflow/flutter-permission-handler")], tags=["Flutter", "OpenSource", "Platform"]),
    dict(slug="oss-just-audio", package="just_audio", title="just_audio: controllable audio with streams", vi="just_audio: audio có thể điều khiển bằng stream", focus="queues, position streams, playlists, speed, and background integration", vi_focus="queue, stream position, playlist, tốc độ và tích hợp background", code="""final player = AudioPlayer();\nawait player.setAudioSource(\n  ConcatenatingAudioSource(children: [\n    AudioSource.uri(Uri.parse(trackUrl)),\n  ]),\n);\nplayer.play();\nplayer.positionStream.listen(updateProgress);""", pitfall="Own player lifecycle and audio focus explicitly; a disposed screen must not keep the stream alive.", vi_pitfall="Quản lý lifecycle player và audio focus rõ ràng; màn hình dispose không được giữ stream sống.", sources=[("just_audio on pub.dev", "https://pub.dev/packages/just_audio"), ("just_audio repository", "https://github.com/ryanheise/just_audio")], tags=["Flutter", "OpenSource", "Media"]),
    dict(slug="oss-video-player", package="video_player", title="video_player: the platform-backed Flutter video primitive", vi="video_player: primitive video Flutter dựa trên platform", focus="controllers, initialization, buffering, subtitles, and lifecycle", vi_focus="controller, khởi tạo, buffering, subtitle và lifecycle", code="""final controller = VideoPlayerController.networkUrl(Uri.parse(url));\nawait controller.initialize();\ncontroller.play();\n\nreturn AspectRatio(\n  aspectRatio: controller.value.aspectRatio,\n  child: VideoPlayer(controller),\n);""", pitfall="Dispose controllers and handle initialization errors; a video widget alone does not manage resources.", vi_pitfall="Dispose controller và xử lý lỗi khởi tạo; video widget không tự quản lý resource.", sources=[("video_player on pub.dev", "https://pub.dev/packages/video_player"), ("Flutter video_player package", "https://github.com/flutter/packages/tree/main/packages/video_player")], tags=["Flutter", "OpenSource", "Media"]),
    dict(slug="oss-camera-plugin", package="camera", title="camera: a real capture pipeline, not just a preview", vi="camera: pipeline chụp thật, không chỉ là preview", focus="controller lifecycle, image streams, permissions, and orientation", vi_focus="lifecycle controller, image stream, permission và orientation", code="""final cameras = await availableCameras();\nfinal controller = CameraController(\n  cameras.first,\n  ResolutionPreset.high,\n  enableAudio: false,\n);\nawait controller.initialize();\nfinal file = await controller.takePicture();""", pitfall="Lock the capture flow to a lifecycle state and test rotation, backgrounding, and denied permission.", vi_pitfall="Gắn capture flow với lifecycle và test xoay màn hình, background, cùng permission bị từ chối.", sources=[("camera on pub.dev", "https://pub.dev/packages/camera"), ("Flutter camera package", "https://github.com/flutter/packages/tree/main/packages/camera")], tags=["Flutter", "OpenSource", "Camera"]),
    dict(slug="oss-file-picker", package="file_picker", title="file_picker: one user intent across six platforms", vi="file_picker: một user intent trên sáu platform", focus="filters, multiple selection, bytes, and platform-specific paths", vi_focus="filter, chọn nhiều file, bytes và path theo platform", code="""final result = await FilePicker.platform.pickFiles(\n  allowMultiple: true,\n  type: FileType.custom,\n  allowedExtensions: ['pdf', 'png'],\n);\nfor (final file in result?.files ?? <PlatformFile>[]) {\n  upload(file.name, file.bytes, file.path);\n}""", pitfall="On web and mobile, a filesystem path may be unavailable; design APIs around bytes or streams.", vi_pitfall="Trên web và mobile, filesystem path có thể không tồn tại; API nên nhận bytes hoặc stream.", sources=[("file_picker on pub.dev", "https://pub.dev/packages/file_picker"), ("file_picker repository", "https://github.com/miguelpruivo/flutter_file_picker")], tags=["Flutter", "OpenSource", "Files"]),
    dict(slug="oss-desktop-multi-window", package="desktop_multi_window", title="desktop_multi_window: isolate desktop surfaces intentionally", vi="desktop_multi_window: quản lý nhiều cửa sổ desktop có chủ đích", focus="window lifecycle, arguments, isolate boundaries, and platform constraints", vi_focus="lifecycle cửa sổ, arguments, ranh giới isolate và giới hạn platform", code="""final window = await WindowController.create(\n  WindowConfiguration(arguments: jsonEncode({'route': '/settings'})),\n);\nawait window.show();\nawait window.setTitle('Settings');""", pitfall="Treat each window as an independent lifecycle; do not assume the main widget tree is shared.", vi_pitfall="Xem mỗi cửa sổ là lifecycle độc lập; đừng giả định widget tree chính được chia sẻ.", sources=[("desktop_multi_window on pub.dev", "https://pub.dev/packages/desktop_multi_window"), ("desktop_multi_window repository", "https://github.com/MixinNetwork/flutter-plugins/tree/master/packages/desktop_multi_window")], tags=["Flutter", "OpenSource", "Desktop"]),
    dict(slug="oss-flutter-rust-bridge", package="flutter_rust_bridge", title="flutter_rust_bridge: typed Rust without hand-written FFI glue", vi="flutter_rust_bridge: Rust có kiểu mà không phải tự viết FFI glue", focus="code generation, async Rust, streams, error boundaries, and native builds", vi_focus="code generation, Rust async, stream, error boundary và native build", code="""#[flutter_rust_bridge::frb]\npub async fn hash_file(path: String) -> anyhow::Result<String> {\n    Ok(sha256::digest(std::fs::read(path)?))\n}\n\nfinal digest = await api.hashFile(path: filePath);""", pitfall="Define the native build matrix early; FFI success on macOS does not prove Android or Windows packaging.", vi_pitfall="Chốt build matrix native sớm; FFI chạy trên macOS không chứng minh package Android/Windows đúng.", sources=[("flutter_rust_bridge on pub.dev", "https://pub.dev/packages/flutter_rust_bridge"), ("flutter_rust_bridge repository", "https://github.com/fzy1121/flutter_rust_bridge")], tags=["Flutter", "OpenSource", "Rust"]),
    dict(slug="oss-melos-monorepo", package="melos", title="Melos: make a Flutter monorepo a product boundary", vi="Melos: biến Flutter monorepo thành ranh giới sản phẩm", focus="workspace scripts, package graph, selective tests, and releases", vi_focus="script workspace, package graph, test chọn lọc và release", code="""name: flutter_workspace\npackages:\n  - apps/**\n  - packages/**\n\nscripts:\n  analyze: melos exec -- flutter analyze\n  test: melos exec --fail-fast -- flutter test\n  changed: melos exec --since=main -- flutter test""", pitfall="A monorepo without ownership and dependency rules is only a larger folder; enforce boundaries in CI.", vi_pitfall="Monorepo không có ownership và luật dependency chỉ là folder lớn hơn; hãy enforce bằng CI.", sources=[("melos on pub.dev", "https://pub.dev/packages/melos"), ("Melos documentation", "https://melos.invertase.dev/")], tags=["Flutter", "OpenSource", "Monorepo"]),
    dict(slug="oss-very-good-cli", package="very_good_cli", title="Very Good CLI: opinionated Flutter scaffolding", vi="Very Good CLI: scaffolding Flutter có opinion", focus="project templates, flavors, testing defaults, and CI conventions", vi_focus="template project, flavor, mặc định testing và quy ước CI", code="""dart pub global activate very_good_cli\nvery_good create flutter_app my_app\ncd my_app\nvery_good packages get\nvery_good test --coverage""", pitfall="Adopt the conventions selectively; the generator should reduce decisions, not erase your architecture.", vi_pitfall="Chỉ nhận convention phù hợp; generator nên giảm quyết định, không xóa kiến trúc của bạn.", sources=[("very_good_cli on pub.dev", "https://pub.dev/packages/very_good_cli"), ("Very Good CLI repository", "https://github.com/VeryGoodOpenSource/very_good_cli")], tags=["Flutter", "OpenSource", "Tooling"]),
    dict(slug="oss-fvm-flutter-version-manager", package="fvm", title="FVM: pin Flutter versions per repository", vi="FVM: ghim Flutter version theo từng repository", focus="version files, CI parity, team onboarding, and migration cadence", vi_focus="file version, parity với CI, onboarding team và nhịp migration", code="""fvm use stable\nfvm flutter pub get\nfvm flutter test\nfvm flutter build apk --release""", pitfall="Pin the version in CI and developer docs too; a local FVM setting alone is not reproducible.", vi_pitfall="Ghim version cả ở CI và docs; setting FVM trên máy cá nhân chưa đủ reproducible.", sources=[("FVM on pub.dev", "https://pub.dev/packages/fvm"), ("FVM documentation", "https://fvm.app/")], tags=["Flutter", "OpenSource", "Tooling"]),
    dict(slug="oss-mocktail", package="mocktail", title="Mocktail: readable Dart mocks without generated files", vi="Mocktail: mock Dart dễ đọc mà không cần file generated", focus="fakes, stubbing, verification, fallback values, and test boundaries", vi_focus="fake, stub, verify, fallback value và ranh giới test", code="""class MockUserApi extends Mock implements UserApi {}\n\nfinal api = MockUserApi();\nwhen(() => api.fetchUser('42')).thenAnswer((_) async => user);\nfinal result = await repository.load('42');\nverify(() => api.fetchUser('42')).called(1);""", pitfall="Mock at the boundary you own; mocking every internal class makes refactors expensive.", vi_pitfall="Mock ở boundary do bạn sở hữu; mock mọi class nội bộ làm refactor đắt đỏ.", sources=[("mocktail on pub.dev", "https://pub.dev/packages/mocktail"), ("Mocktail repository", "https://github.com/felangel/mocktail")], tags=["Flutter", "OpenSource", "Testing"]),
    dict(slug="oss-golden-toolkit", package="golden_toolkit", title="Golden Toolkit: visual regression with intent", vi="Golden Toolkit: regression hình ảnh có chủ đích", focus="device matrices, fonts, surface variants, and readable golden diffs", vi_focus="ma trận thiết bị, font, biến thể surface và diff golden dễ đọc", code="""testGoldens('profile variants', (tester) async {\n  await loadAppFonts();\n  await tester.pumpWidgetBuilder(const ProfileCard());\n  await screenMatchesGolden(tester, 'profile-card');\n});""", pitfall="Freeze fonts and data before capture; otherwise a golden diff measures noise instead of UI change.", vi_pitfall="Cố định font và data trước khi chụp; nếu không diff sẽ đo nhiễu thay vì thay đổi UI.", sources=[("golden_toolkit on pub.dev", "https://pub.dev/packages/golden_toolkit"), ("Golden Toolkit repository", "https://github.com/eBay/flutter_glove_box/tree/master/packages/golden_toolkit")], tags=["Flutter", "OpenSource", "Testing"]),
    dict(slug="oss-pigeon-typed-platform-channels", package="pigeon", title="Pigeon: typed platform channels generated from one schema", vi="Pigeon: platform channel có kiểu sinh từ một schema", focus="Dart/native codegen, API contracts, task queues, and versioning", vi_focus="codegen Dart/native, contract API, task queue và versioning", code="""@HostApi()\nabstract class SecureBiometrics {\n  bool isAvailable();\n  @async\n  bool authenticate(String reason);\n}\n\n// dart run pigeon --input pigeons/biometrics.dart""", pitfall="Version the schema like an API; adding a breaking method can desync released native binaries.", vi_pitfall="Version schema như một API; thêm method breaking có thể làm lệch binary native đã phát hành.", sources=[("pigeon on pub.dev", "https://pub.dev/packages/pigeon"), ("Pigeon repository", "https://github.com/flutter/packages/tree/main/packages/pigeon")], tags=["Flutter", "OpenSource", "Platform"]),
    dict(slug="oss-flutter-hooks", package="flutter_hooks", title="flutter_hooks: reusable stateful behavior as tiny hooks", vi="flutter_hooks: tái sử dụng behavior có state bằng hook nhỏ", focus="hook lifecycle, controller ownership, effects, and composable UI logic", vi_focus="lifecycle hook, ownership controller, effect và UI logic ghép được", code="""class SearchField extends HookWidget {\n  const SearchField({super.key});\n  @override\n  Widget build(BuildContext context) {\n    final controller = useTextEditingController();\n    final focusNode = useFocusNode();\n    useEffect(() {\n      focusNode.requestFocus();\n      return null;\n    }, const []);\n    return TextField(controller: controller, focusNode: focusNode);\n  }\n}""", pitfall="Hooks follow call order; never call them conditionally or inside loops.", vi_pitfall="Hook phụ thuộc thứ tự gọi; không gọi hook có điều kiện hoặc trong vòng lặp.", sources=[("flutter_hooks on pub.dev", "https://pub.dev/packages/flutter_hooks"), ("flutter_hooks repository", "https://github.com/rrousselGit/flutter_hooks")], tags=["Flutter", "OpenSource", "UI"]),
    dict(slug="oss-equatable", package="equatable", title="Equatable: value semantics for Dart state objects", vi="Equatable: value semantics cho state object Dart", focus="equality, props, sealed states, and predictable rebuild checks", vi_focus="equality, props, sealed state và kiểm tra rebuild dễ đoán", code="""class UserLoaded extends Equatable {\n  const UserLoaded(this.user);\n  final User user;\n  @override\n  List<Object?> get props => [user.id, user.updatedAt];\n}""", pitfall="Include every field that changes UI meaning; incomplete props create stale widgets and confusing tests.", vi_pitfall="Đưa mọi field ảnh hưởng UI vào props; thiếu field sẽ tạo widget cũ và test khó hiểu.", sources=[("equatable on pub.dev", "https://pub.dev/packages/equatable"), ("Equatable repository", "https://github.com/felangel/equatable")], tags=["Flutter", "OpenSource", "Dart"]),
    dict(slug="oss-json-serializable", package="json_serializable", title="json_serializable: boring JSON that survives refactors", vi="json_serializable: JSON nhàm chán nhưng bền qua refactor", focus="generated codecs, converters, checked mode, and API model boundaries", vi_focus="codec generated, converter, checked mode và boundary API model", code="""@JsonSerializable()\nclass User {\n  const User({required this.id, required this.displayName});\n  final String id;\n  final String displayName;\n  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);\n  Map<String, dynamic> toJson() => _$UserToJson(this);\n}""", pitfall="Keep transport DTOs separate from domain entities when API evolution is frequent.", vi_pitfall="Tách transport DTO khỏi domain entity khi API thay đổi thường xuyên.", sources=[("json_serializable on pub.dev", "https://pub.dev/packages/json_serializable"), ("json_serializable repository", "https://github.com/google/json_serializable.dart")], tags=["Flutter", "OpenSource", "Codegen"]),
    dict(slug="oss-build-runner", package="build_runner", title="build_runner: make code generation a deterministic build step", vi="build_runner: biến code generation thành build step deterministic", focus="watch mode, delete-conflicting-outputs, CI, and generated ownership", vi_focus="watch mode, delete-conflicting-outputs, CI và ownership file generated", code="""dart run build_runner build --delete-conflicting-outputs\ndart run build_runner watch --delete-conflicting-outputs""", pitfall="Do not manually edit generated files; fix the source annotation or builder configuration instead.", vi_pitfall="Không sửa file generated bằng tay; hãy sửa annotation hoặc cấu hình builder.", sources=[("build_runner on pub.dev", "https://pub.dev/packages/build_runner"), ("build repository", "https://github.com/dart-lang/build")], tags=["Flutter", "OpenSource", "Codegen"]),
    dict(slug="oss-intl-localization", package="intl", title="intl: format locale-sensitive data deliberately", vi="intl: format data theo locale một cách có chủ đích", focus="dates, numbers, plurals, locale initialization, and testable formats", vi_focus="date, number, plural, khởi tạo locale và format có thể test", code="""final amount = NumberFormat.currency(\n  locale: 'vi_VN',\n  symbol: '₫',\n).format(1250000);\nfinal date = DateFormat.yMMMMd('en_US').format(order.createdAt);""", pitfall="Never concatenate translated strings with numbers or dates; use ICU messages and locale-aware formatters.", vi_pitfall="Đừng nối chuỗi dịch với number/date; dùng ICU message và formatter theo locale.", sources=[("intl on pub.dev", "https://pub.dev/packages/intl"), ("Dart intl package", "https://github.com/dart-lang/i18n/tree/main/pkgs/intl")], tags=["Flutter", "OpenSource", "Localization"]),
    dict(slug="oss-flutter-animations", package="animations", title="animations: reusable Material motion patterns", vi="animations: pattern motion Material có thể tái sử dụng", focus="OpenContainer, shared axis, fade-through, and route transitions", vi_focus="OpenContainer, shared axis, fade-through và chuyển route", code="""return OpenContainer<bool>(\n  closedBuilder: (_, open) => ListTile(\n    title: const Text('Open details'),\n    onTap: open,\n  ),\n  openBuilder: (_, close) => const DetailsPage(),\n);""", pitfall="Motion must preserve hierarchy and state; do not animate every surface just because the package makes it easy.", vi_pitfall="Motion phải giữ hierarchy và state; đừng animate mọi surface chỉ vì package làm điều đó dễ.", sources=[("animations on pub.dev", "https://pub.dev/packages/animations"), ("Flutter animations package", "https://github.com/flutter/packages/tree/main/packages/animations")], tags=["Flutter", "OpenSource", "Animation"]),
    dict(slug="oss-skeletonizer", package="skeletonizer", title="skeletonizer: loading UI from the real widget tree", vi="skeletonizer: loading UI từ chính widget tree thật", focus="fake data, skeleton annotations, layout stability, and accessibility", vi_focus="fake data, annotation skeleton, layout ổn định và accessibility", code="""Skeletonizer(\n  enabled: state.isLoading,\n  child: ListView.builder(\n    itemCount: state.isLoading ? 6 : state.items.length,\n    itemBuilder: (_, index) => ProductTile(\n      product: state.isLoading ? Product.fake() : state.items[index],\n    ),\n  ),\n);""", pitfall="Use structurally realistic fake data; empty strings create skeletons that do not match the loaded layout.", vi_pitfall="Fake data phải có cấu trúc giống thật; chuỗi rỗng tạo skeleton không khớp layout loaded.", sources=[("skeletonizer on pub.dev", "https://pub.dev/packages/skeletonizer"), ("Skeletonizer repository", "https://github.com/Milad-Akarie/skeletonizer")], tags=["Flutter", "OpenSource", "UX"]),
    dict(slug="oss-image-picker", package="image_picker", title="image_picker: a small API over messy media sources", vi="image_picker: API nhỏ cho các nguồn media phức tạp", focus="camera/gallery intent, lost data recovery, compression, and permissions", vi_focus="intent camera/gallery, khôi phục lost data, nén ảnh và permission", code="""final picker = ImagePicker();\nfinal image = await picker.pickImage(\n  source: ImageSource.gallery,\n  maxWidth: 2000,\n  imageQuality: 85,\n);\nif (image != null) upload(await image.readAsBytes());""", pitfall="Handle Android activity recreation with retrieveLostData and validate file size before upload.", vi_pitfall="Xử lý activity recreation Android bằng retrieveLostData và kiểm tra size trước khi upload.", sources=[("image_picker on pub.dev", "https://pub.dev/packages/image_picker"), ("Flutter image_picker package", "https://github.com/flutter/packages/tree/main/packages/image_picker")], tags=["Flutter", "OpenSource", "Media"]),
    dict(slug="oss-url-launcher", package="url_launcher", title="url_launcher: platform intent with a fallback contract", vi="url_launcher: platform intent với hợp đồng fallback", focus="canLaunchUrl, launch modes, web URLs, and unavailable handlers", vi_focus="canLaunchUrl, launch mode, web URL và handler không khả dụng", code="""final uri = Uri.parse('mailto:support@example.com');\nif (await canLaunchUrl(uri)) {\n  await launchUrl(uri, mode: LaunchMode.externalApplication);\n} else {\n  showUnsupportedAction();\n}""", pitfall="A canLaunch check is advisory; still handle launch failure and configure platform query declarations.", vi_pitfall="canLaunch chỉ mang tính gợi ý; vẫn phải xử lý launch fail và khai báo query của platform.", sources=[("url_launcher on pub.dev", "https://pub.dev/packages/url_launcher"), ("Flutter url_launcher package", "https://github.com/flutter/packages/tree/main/packages/url_launcher/url_launcher")], tags=["Flutter", "OpenSource", "Platform"]),
    dict(slug="oss-connectivity-plus", package="connectivity_plus", title="connectivity_plus: network type is not internet reachability", vi="connectivity_plus: loại mạng không đồng nghĩa có internet", focus="connectivity streams, offline UX, reachability checks, and platform nuance", vi_focus="stream kết nối, UX offline, kiểm tra reachability và khác biệt platform", code="""final subscription = Connectivity().onConnectivityChanged.listen((types) {\n  final hasTransport = types.any((type) =>\n      type == ConnectivityResult.wifi || type == ConnectivityResult.mobile);\n  banner.show(hasTransport ? 'Online' : 'Offline');\n});\n\n// Cancel subscription in dispose().""", pitfall="Do not use connectivity type as proof that an API call will succeed; confirm with a request or health check.", vi_pitfall="Đừng xem connectivity type là bằng chứng API sẽ chạy; hãy xác nhận bằng request hoặc health check.", sources=[("connectivity_plus on pub.dev", "https://pub.dev/packages/connectivity_plus"), ("connectivity_plus repository", "https://github.com/fluttercommunity/plus_plugins/tree/main/packages/connectivity_plus")], tags=["Flutter", "OpenSource", "Offline"]),
]


def frontmatter(item: dict, vi: bool) -> str:
    title = item["vi"] if vi else item["title"]
    description = (
        f"Showcase {item['package']} in a production-minded Flutter architecture: {item['focus']}."
        if not vi
        else f"Showcase {item['package']} trong kiến trúc Flutter thực tế: {item['vi_focus']}."
    )
    data = {
        "title": title,
        "description": description,
        "seoDescription": description,
        "keywords": [item["package"], "Flutter open source", "Flutter library", "Flutter tutorial"],
        "category": "Open Source",
        "topic": "Flutter OSS",
        "level": "Intermediate",
        "author": AUTHOR,
        "publishDate": DATE,
        "emoji": "🧩",
        "tags": item["tags"],
        "sources": [{"name": name, "url": url} for name, url in item["sources"]],
        "related": [
            {"slug": "flutter-state-management-decision-guide", "title": "State management decision guide"},
            {"slug": "flutter-testing-widget-golden-integration", "title": "Widget and golden testing"},
        ],
        "draft": False,
    }
    return "---\n" + yaml.safe_dump(data, allow_unicode=True, sort_keys=False).strip() + "\n---\n"


def body(item: dict, vi: bool) -> str:
    title = item["vi"] if vi else item["title"]
    focus = item["vi_focus"] if vi else item["focus"]
    pitfall = item["vi_pitfall"] if vi else item["pitfall"]
    if vi:
        return f"""# {title}\n\n`{item['package']}` đáng chú ý vì nó giải quyết {focus}. Bài này trình bày cách đặt package vào đúng boundary của một ứng dụng Flutter production thay vì chỉ copy một snippet vào màn hình.\n\n![FlutterCook open-source showcase]({HERO})\n\n## Package này sở hữu phần nào?\n\n- Giữ API của package ở một adapter hoặc feature boundary có tên rõ ràng.\n- Đưa lifecycle, lỗi và trạng thái loading vào contract mà UI có thể kiểm thử.\n- Chỉ expose capability cần thiết; đừng để toàn app phụ thuộc vào chi tiết triển khai.\n\n## Snippet bắt đầu\n\n```dart\n{item['code']}\n```\n\n## Checklist trước khi ship\n\n1. Đọc README và changelog của package đúng version đang pin.\n2. Viết một test cho lifecycle, lỗi và hành vi khi app về background.\n3. Kiểm tra Android, iOS, web hoặc desktop đúng platform mà app hỗ trợ.\n4. Ghi lại owner, upgrade cadence và kế hoạch rollback trong repo.\n\n## Pitfall hay gặp\n\n{pitfall}\n\n## Kết luận\n\nThư viện OSS tốt không thay thế kiến trúc. Nó giúp một boundary khó trở nên rõ ràng, có thể quan sát và dễ thay thế hơn.\n"""
    return f"""# {title}\n\n`{item['package']}` is useful because it focuses on {focus}. The important engineering move is to place the package behind a clear boundary, so your Flutter UI depends on a stable capability rather than a vendor-shaped API.\n\n![FlutterCook open-source showcase]({HERO})\n\n## What the library should own\n\n- Keep package calls inside a named adapter or feature boundary.\n- Make lifecycle, errors, and loading state part of a testable contract.\n- Expose only the capability the app needs; hide implementation details from the whole tree.\n\n## A focused starting point\n\n```dart\n{item['code']}\n```\n\n## Production checklist\n\n1. Read the README and changelog for the exact version you pin.\n2. Add one test for lifecycle, failure, and app background/foreground behavior.\n3. Verify every platform your product supports, not only the developer machine.\n4. Record ownership, upgrade cadence, and rollback notes in the repository.\n\n## Common pitfall\n\n{pitfall}\n\n## Takeaway\n\nA good open-source library does not replace architecture. It makes one difficult boundary clearer, observable, and easier to replace.\n"""


def write_one(item: dict, directory: Path, vi: bool) -> bool:
    path = directory / f"{item['slug']}.md"
    if path.exists():
        return False
    path.write_text(frontmatter(item, vi) + "\n" + body(item, vi), encoding="utf-8")
    return True


def main() -> None:
    created = 0
    for item in TOPICS:
        created += int(write_one(item, OUT_EN, False))
        created += int(write_one(item, OUT_VI, True))
    print(f"topics={len(TOPICS)} created={created} expected={len(TOPICS) * 2}")


if __name__ == "__main__":
    main()
